--liquibase formatted sql

--changeset roadmap:1.0-schema
create table authors
(
    id   bigint generated by default as identity primary key,
    name varchar(255) not null
);

create table books
(
    id               bigint generated by default as identity primary key,
    title            varchar(255) not null,
    publication_year int          not null,
    author_id        bigint       not null references authors (id)
);

create table genres
(
    id   bigint generated by default as identity primary key,
    name varchar(100) not null unique
);

create table book_genres
(
    book_id  bigint not null references books (id),
    genre_id bigint not null references genres (id),
    primary key (book_id, genre_id)
);
